// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfxPGnIYUonWz-WGpF-fJMsxYDHK-JsRo',
    appId: '1:994997751617:web:dc0de8865fba34825c9bc0',
    messagingSenderId: '994997751617',
    projectId: 'flutter-uber-clone-with-cd880',
    authDomain: 'flutter-uber-clone-with-cd880.firebaseapp.com',
    databaseURL: 'https://flutter-uber-clone-with-cd880-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-with-cd880.appspot.com',
    measurementId: 'G-RVCQWDKJJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv3FpthXYiAnaNewwqgReknZueTogyhy8',
    appId: '1:994997751617:android:deaaa6b53e2f34495c9bc0',
    messagingSenderId: '994997751617',
    projectId: 'flutter-uber-clone-with-cd880',
    databaseURL: 'https://flutter-uber-clone-with-cd880-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-with-cd880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmkjcC7Tvd731Txu-PT6M_sQffHbn_5mw',
    appId: '1:994997751617:ios:d19ca1212f7957e75c9bc0',
    messagingSenderId: '994997751617',
    projectId: 'flutter-uber-clone-with-cd880',
    databaseURL: 'https://flutter-uber-clone-with-cd880-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-with-cd880.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmkjcC7Tvd731Txu-PT6M_sQffHbn_5mw',
    appId: '1:994997751617:ios:d19ca1212f7957e75c9bc0',
    messagingSenderId: '994997751617',
    projectId: 'flutter-uber-clone-with-cd880',
    databaseURL: 'https://flutter-uber-clone-with-cd880-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-with-cd880.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfxPGnIYUonWz-WGpF-fJMsxYDHK-JsRo',
    appId: '1:994997751617:web:49100e0787041da65c9bc0',
    messagingSenderId: '994997751617',
    projectId: 'flutter-uber-clone-with-cd880',
    authDomain: 'flutter-uber-clone-with-cd880.firebaseapp.com',
    databaseURL: 'https://flutter-uber-clone-with-cd880-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-with-cd880.appspot.com',
    measurementId: 'G-LQRZB7LXWY',
  );
}
